services:
  db:
    #build: ./db
    image: postgis/postgis:15-3.3
    container_name: geoff-db
    env_file:
      - ./db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/sql/init-users.sh:/docker-entrypoint-initdb.d/init-users.sh
    networks:
      - geoff-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d geoff"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: ./db/etl
    container_name: geoff-etl
    depends_on:
      - db
    env_file:
      - ./db/etl/.env
    networks:
      - geoff-prod
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: geoff-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - geoff-prod
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    container_name: geoff-frontend
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    networks:
      - geoff-prod
    restart: unless-stopped

volumes:
  db-data:

networks:
  geoff-prod:
    driver: bridge