services:
  db:
    #build: ./db
    image: postgis/postgis:15-3.3
    container_name: geoff-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl:
    build: ./db/etl
    container_name: geoff-etl
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    volumes:
      - ./db/etl:/app
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: geoff-backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: geoff-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data: